### ISSUE TITLE
Minimum example doesn't work 

### ISSUE THREAD

**Issue by zipping-suger** [vthorey/benderopt#6]
Hi, I tried to run the file minimizer.py, however, it raised an error:

```python
Traceback (most recent call last):
  File "/home/zippingsugar/anaconda2/envs/HLSTS/lib/python2.7/site-packages/benderopt-1.3.2-py2.7.egg/benderopt/minimizer.py", line 44, in <module>
    f, optimization_problem_parameters=optimization_problem_parameters, number_of_evaluation=100)
  File "/home/zippingsugar/anaconda2/envs/HLSTS/lib/python2.7/site-packages/benderopt-1.3.2-py2.7.egg/benderopt/minimizer.py", line 19, in minimize
    optimization_problem = OptimizationProblem.from_list(optimization_problem_parameters)
  File "/home/zippingsugar/anaconda2/envs/HLSTS/lib/python2.7/site-packages/benderopt-1.3.2-py2.7.egg/benderopt/base/optimization_problem.py", line 259, in from_list
    return cls(parameters)
  File "/home/zippingsugar/anaconda2/envs/HLSTS/lib/python2.7/site-packages/benderopt-1.3.2-py2.7.egg/benderopt/base/optimization_problem.py", line 80, in __init__
    raise ValidationError(message="'parameters' must be a list of Parameter")
benderopt.validation.utils.ValidationError: 'parameters' must be a list of Parameter
```

I guess there were some modifications in the code and the example wasn't updated in time.

**Comment by zipping-suger** [comment]
> Hi, I tried to run the file minimizer.py, however, it raised an error:
> 
> ```python
> Traceback (most recent call last):
>   File "/home/zippingsugar/anaconda2/envs/HLSTS/lib/python2.7/site-packages/benderopt-1.3.2-py2.7.egg/benderopt/minimizer.py", line 44, in <module>
>     f, optimization_problem_parameters=optimization_problem_parameters, number_of_evaluation=100)
>   File "/home/zippingsugar/anaconda2/envs/HLSTS/lib/python2.7/site-packages/benderopt-1.3.2-py2.7.egg/benderopt/minimizer.py", line 19, in minimize
>     optimization_problem = OptimizationProblem.from_list(optimization_problem_parameters)
>   File "/home/zippingsugar/anaconda2/envs/HLSTS/lib/python2.7/site-packages/benderopt-1.3.2-py2.7.egg/benderopt/base/optimization_problem.py", line 259, in from_list
>     return cls(parameters)
>   File "/home/zippingsugar/anaconda2/envs/HLSTS/lib/python2.7/site-packages/benderopt-1.3.2-py2.7.egg/benderopt/base/optimization_problem.py", line 80, in __init__
>     raise ValidationError(message="'parameters' must be a list of Parameter")
> benderopt.validation.utils.ValidationError: 'parameters' must be a list of Parameter
> ```
> 
> I guess there were some modifications in the code and the example wasn't updated in time.
